### PR TITLE
Feature 273: User are able to delete pictograms they have created

### LINKED ISSUE #273: As a guardian I would like to be able to delete pictograms I've uploaded so that I can remove wrongly uploaded / outdated pictograms

### PR DESCRIPTION
**Pull request by AdrianPlesner**
Closes #273 
This is merely the frontend implementation of this feature, for it to be working properly the following issue in the web-api needs to be completed aau-giraf/web-api#162

### CODE REVIEW

**Comment by Determinatoro** [comment]
Please use the following checklist, @ZohraAmini. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] Error messages in the code are understandable

**Code Maintainability**

- [x] Has all the added code been properly commented

Only check one of the items below:

- [x] The functionality does **not** need be covered by tests
- [ ] The functionality needs to be covered by tests

Only use if the functionality needs to be covered by tests:

- [x] All functionality is covered by tests
- [x] The tests has sensible names
- [x] By reading the tests you know what they cover
- [x] The tests cover sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Comment by Determinatoro** [comment]
Please use the following checklist, @Mustafa-ALD. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] Error messages in the code are understandable

**Code Maintainability**

- [x] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need be covered by tests
- [x] The functionality needs to be covered by tests

Only use if the functionality needs to be covered by tests:

- [x] All functionality is covered by tests
- [x] The tests has sensible names
- [x] By reading the tests you know what they cover
- [x] The tests cover sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Comment by Mustafa-ALD** [comment]
LGTM

**Review by Mustafa-ALD — DISMISSED** [review]

**Review by ZohraAmini — COMMENTED** [review]
1. +Stream and -Observable changes
2. I can't create a new weekplan
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.

**Comment by AdrianPlesner** [comment]
Stream/Observable should be fixed.
@ZohraAmini  I have been unable to recreate your other bug, please try again with the new commit.

**Comment by ZohraAmini** [comment]
I just fetched your new commits, it (creating new weekplan) doesn't work:(

**Review by ZohraAmini — APPROVED** [review]

**Review by Mustafa-ALD — APPROVED** [review]

**Pull request merged**
