### PR TITLE
Feature 514: Popped the context for the activity icon setting options.

### LINKED ISSUE #514: Changing 'Tegn for udførelse' does not move to previous screen
**Describe the bug**
When changing the 'Tegn for udførelse' setting, the screen is not popped.

**To Reproduce**
1. Go to Settings and press 'Tegn for udførelse'.
2. Change to any other setting.
3. See that the screen is not popped to the previous screen.

**Expected behavior**
The screen is popped so that the setting appears.

**Actual behavior**
Nothing happens to the screen. The setting is changed, but the screen is not popped.

**Environment (please complete the following information):**
- OS: Android and IOS.
- Emulator? Yes

### PR DESCRIPTION
**Pull request by AdrianPlesner**
Screen is now popped. 
Closes #514

### CODE REVIEW

**Comment by AdrianPlesner** [comment]
Closes #514

**Comment by ghost** [comment]
Please use the following checklist @Emil7370 . Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [x] The tests covers sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Comment by ghost** [comment]
Please use the following checklist @ZohraAmini . Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [x] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [x] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by ZohraAmini — COMMENTED** [review]
Missing unit tests

**Review by ZohraAmini — DISMISSED** [review]

**Comment by AdrianPlesner** [comment]
We have added tests and refactored and tested the other setting screens as these didn't test if the screen was popped either.

**Review by ZohraAmini — APPROVED** [review]

**Review by Emil7370 — APPROVED** [review]

**Pull request merged**
