### PR TITLE
Feature 648: Rettet grammatiske fejl i weekplanner

### LINKED ISSUE #648: As a user I would like messages that are displayed to me to be consistent and grammatically correct
**Is your feature request related to a problem? Please describe.**
It seems a bit lazy to not use the correct plural or singular form when managing items in the application, such as deleting and copying. There are also many instances where a question mark is missing. 

**Describe the solution you'd like**
A ternary expression should be able to detect whether one or more items are being managed, and the parentheses with "(er)" and titles on warnings should therefore be of the correct form.

Generally, just go through the messages and warnings and make sure they use correct punctuation and grammar.

**Additional context**
Some cases that were found:

Should be "Aflys aktivitet" and "Vil du markere 1 aktivitet som aflyst?"
image

Should be "Slet aktivitet" and "Vil du slette 1 aktivitet?"
image

Should be "Slet ugeplan" and "Vil du slette 1 ugeplan?"
image

### PR DESCRIPTION
**Pull request by fatimaosman99**
Feature #648: Rettede små grammatiske fejl så den nu printer f.eks. "2 aktiviteter" istedet for 2 aktivitet(er). Tilføjede sprøgsmålstegn der hvor den manglede. closes #648

### CODE REVIEW

**Review by MathiasNielsen1206 — CHANGES_REQUESTED** [review]
feature/648 er fikset, men kan se der er ændret i en del filer, med hvad der virker til at have noget med IOS at gøre.  er ikke sikker på om det er sikkert at pushe med op til development eller ej.  så enten skal vi undgå at pushe de fil ændringer med, eller også skal vi være sikre på at det ikke "ødelægger" noget på development branchen 

Code Design 

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

Code Readability 

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution

Code Maintainability

- [x] Has all the added code been properly commented

Only check one of the items below:

- [x] The functionality does not need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

Functionality

For this part, open the app, and test:
- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Review by MathiasNielsen1206 — DISMISSED** [review]
loooks very nice now!

**Review by Casper0913 — DISMISSED** [review]
Looks good

**Review by MathiasNielsen1206 — DISMISSED** [review]
yes

**Review by Casper0913 — DISMISSED** [review]

**Review by MathiasNielsen1206 — APPROVED** [review]
yes

**Review by MagnusMat — APPROVED** [review]

**Pull request merged**
