### PR TITLE
Updated core

### PR DESCRIPTION
**Pull request by boginw**
# Upgrade guide v0.0.1 -> v0.0.2

## Dependency Injector
Before, we used to feed BLoC's to the screen by using the `BlocProvider` and `BlocProviderTree.` These are now removed. Instead, you should use the dependency injector. This provides a much cleaner experience and allows for dependency injection to screens, ie., passing data to a screen.

Example:
```dart
SettingsBloc settingsBloc = BlocProviderTree.of<SettingsBloc>(context);
```

Becomes:
```dart
SettingsBloc settingsBloc = di.getDependency<SettingsBloc>();
```

This also enforces developers to register their global BLoC's.

### Register Dependencies

All registering of dependencies are to be made in `bootstrap.dart`. To regiter a singleton, you can use the following:

```dart
di.registerSingleton((Injector i) {
    return AuthBloc(i.getDependency<Api>());
});
```

To register a normal dependency, use the following:

```dart
di.registerDependency((Injector i) {
    return OneTimeThing();
});
```

## Navigation wrappers

As of now, there was no obvious way to send data between screens. This has been addressed in the newest release of the core. We've made a wrapper to the Navigation class, which exposes two methods:

* `Routes.push,` for navigating to a new page,
* `Routes.pop,` for returning to the previous page.

Unfortunately for many, we also removed the named routes to be able to send data on push.

The reason for wrapping is to withhold the ability to append or remove features in the future.

### How to use it

To go to a new page, without anything fancy, you call `Routes.push` with the current `context,` and the constructed _screen_ you wish to go to:

```dart
Routes.push(context, WeekplanScreen());
```

Now, feeding data to the next screen becomes trivial. In the example below, we feed the `WeekplanScreen` screen some data in it's the constructor.

```dart
Routes.push(context, WeekplanScreen(data: dataVariable));
```

Returning data to the previous screen requires the previous screen to listen for the results of the current. In the example below, we see a listener waiting for the `PictogramSearch` screen to return.

```dart
PictogramModel model = await Routes.push<PictogramModel>(context, PictogramSearchScreen());
```

And in the `PictogramSearch` screen, we use the `Routes.pop` function, to return our results to the previous screen.

```dart
Routes.pop(context, model);
```

## Authentication

The app now resolves authentication status automatically. Meaning if call `logout`, the app will automatically redirect the user to the login screen. 

This eliminates the need to ensure proper redirects to the login when wanting to perform a logout.

### CODE REVIEW

**Review by thomaslhansen — DISMISSED** [review]
Is okay, however this commit will resolve en conflicts in other groups like #23 and possibly other.

**Comment by TobiasPalludan** [comment]
@aau-giraf/sw613f19 you guys have been assigned to review this PR, and @ralled96 has the main responsibility that it is done. You may assign it internally in the group as you like, but I will contact @ralled96 about any issues.

**Review by ralled96 — CHANGES_REQUESTED** [review]
Looks good, but we are missing some comments on the core functionality.

**Comment by boginw** [comment]
> Looks good, but we are missing some comments on the core functionality.

Please specify what comments you're missing

**Comment by LukasRH** [comment]
It would be nice with some comments explaining the new routes.dart, not only for us but also looking ahead when the next semester have to take over the project.

**Review by ralled96 — APPROVED** [review]

**Review by thomaslhansen — APPROVED** [review]
We should not use static urls within the code and it should be added an environment variable. But @Tricky12321 is apparently on the job, so for now approved.

**Pull request merged**
