### PR TITLE
Feature 177

### LINKED ISSUE #177: As a guardian I would like the weekplans on "vælg ugeplan" screen to show the week and year of each plan so that I can easily find the right plan

### PR DESCRIPTION
**Pull request by giano574**
Resolves #177 
- Added text for week/year.
- Added tests that check for new week/year.
Screenshot_1582277448

### CODE REVIEW

**Review by holyfailer — DISMISSED** [review]
GUI look good

**Comment by giano574** [comment]
Should not be merged until PR #297 is approved

**Review by frederikspang — DISMISSED** [review]

**Comment by giano574** [comment]
Text in "tilføj ugeplan" now behaves properly
Screenshot_1582548458

**Review by frederikspang — APPROVED** [review]

**Review by holyfailer — APPROVED** [review]
PO approve design

**Review by Laexander — APPROVED** [review]

**Pull request merged**
