### PR TITLE
Feature 780: Implemented trustee weekplan screen

### LINKED ISSUE #780: As a Trustee, I would like a weekplan screen, so that I can see my citizen's weekplan
## Description
The trustee would like to be able to see the citizen's weekplan, make changes and switch between citizen's view and trustee view.

## Sub Tasks
*Create your own subtask issues on GitHub and link them here in a list.*
- [x] #827 
- [x] #767 
- [x] #762 
- [x] #760 
- [x] #757

### PR DESCRIPTION
**Pull request by Sijmon**
# Description
- When the logged in user role is a trustee, they are now showed a weekplan screen when navigating to a weekplan

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*
- The authenticateFromPopUp method, has been extended, to use the account api ".role" function, to check for the role of a given username. After which the role is changed to this in the weekplanner.
- Motivation is implementing the trustee role
- No new dependencies

Fixes #780

## Type of change

*Please delete options that are not relevant.*

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration*

- No new function was added.
- A new api endpoint in the account api was added to the account api in the api_client, from issue aau-giraf/api_client#91
    - This function (_api.account.role()) has been added to the mock data, so that tests can use this

**Test Configuration**:
* Toolchain: Android Studio
* SDK: Android 11.0 (R)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if necessary)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works (if necessary)
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Langbakke — DISMISSED** [review]
Virkelig godt. Rent skrevet og fine overskrifter. Bliv ved med det gode arbejde champ

**Comment by Drejer1** [comment]
**Assets**
- [ ] The ``environments.json`` file has the following default values:
```
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}
```

**Code Design** 

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [x] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Review by Drejer1 — CHANGES_REQUESTED** [review]
Ser super ud men har bare lige et spørgsmål.
Er den dækket af tests? Så vidt jeg ved findes trustee ikke til dags dato så hvordan ved vi at den dur?

**Comment by Sijmon** [comment]
> Ser super ud men har bare lige et spørgsmål. Er den dækket af tests? Så vidt jeg ved findes trustee ikke til dags dato så hvordan ved vi at den dur?

Det har du ret i, tests bliver skrevet senere når vi får trustee implementeret helt

**Review by Drejer1 — APPROVED** [review]

**Review by goldflue — APPROVED** [review]
Det er dælme i orden, Sijmon

**Pull request merged**
