### PR TITLE
Feature 580: Newly added citizens appear in the choose citizen list immediately 

### LINKED ISSUE #580: Newly created citizen does not show up right away in the list of citizens
**Describe the bug**
When a new citizen is created, it does not appear in the list of citizens. One is required to log out and then log in again to see the newly created citizen.

**To Reproduce**
1. In the list of citizens, tap "new citizen"
2. Fill in details with valid information (name, username, password)
3. Tap to create a citizen
4. Observe the landing screen of citizens.

**Expected behavior**
The screen with all citizens will include the newly created citizen along with all the others.

**Actual behavior**
The screen with all citizens will only contain all other citizens already existing in the database, with the new citizen unable to be seen.

**Environment (please complete the following information):**
- OS: Android
- Emulator: Android Emulator
- Phone: Emulated Pixel 2
- APK Version: 27

### PR DESCRIPTION
**Pull request by AdrianPlesner**
Fixes #580

### CODE REVIEW

**Comment by LivHolm** [comment]
Please use the following checklist, @smh87. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [x] Error messages in the code are understandable
- [x] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [x] UI messages, that the user might meet, are actually helpful
- [x] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [x] There is well written code in this. Remember to tell the developer!

**Comment by LivHolm** [comment]
Please use the following checklist, @JeppeKLau. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [x] The tests covers sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [x] Error messages in the code are understandable
- [x] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [x] UI messages, that the user might meet, are actually helpful
- [x] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [x] There is well written code in this. Remember to tell the developer!

**Review by JeppeKLau — APPROVED** [review]

**Review by smh87 — CHANGES_REQUESTED** [review]
Er det muligt at udføre unittest?

**Comment by AdrianPlesner** [comment]
1: Fluttter test er widget test og ikke unit test
2: Dette scenarie går ud på at føre data imellem skærme, hvilket test frameworket ikke er ret god til at håndtere

**Review by smh87 — APPROVED** [review]
Se lig om "A quick word on async stubbing " https://pub.dev/packages/mockito i fremtiden kan hjælpe

**Pull request merged**
