### PR TITLE
Feature 485: Created a new errorColor variable 

### LINKED ISSUE #485: There should be defined a errortext color in the custom colors, and this should be used for all errortext
**Is your feature request related to a problem? Please describe.**
The colors for errortext is not defined in the custom colors, and they are therefore not the same through the app.

**Describe the solution you'd like**
There should be a implemented a standard color for the errortext.
This should properly be defined from PO group.

This should then be implemented all the places errortext is shown.
E.g. in the create new citizen screen and new weekplan screen (input_fields_weekplan).
Maybe also other places

**Additional context**
An example of the different colors is shown here where the "vælg billede til ugeplan" has a different red than the errortext for the textfields.
image

### PR DESCRIPTION
**Pull request by Riasalit**
closes #485 
Made a errorColor variable with the standard error color for dart and used for a incorrectly colored text field.
This variable should be used to color furture errors if the standard errorColor in theme is not used.

### CODE REVIEW

**Review by Rosmarium — COMMENTED** [review]
I'm not sure whatever or not the routes should be changed in this pull-request as it is not related ot the issue at hand.

**Comment by JeppeKLau** [comment]
> 
> 
> I'm not sure whatever or not the routes should be changed in this pull-request as it is not related ot the issue at hand.

The change was made to get the app actually up and running. However, the CI actions fails on the testing making it not viable to go ahead with this pull request.

**Review by JeppeKLau — CHANGES_REQUESTED** [review]
The CI actions need to all complete in order to let this through and currently they do not.

**Review by Rosmarium — APPROVED** [review]

**Review by JeppeKLau — APPROVED** [review]

**Comment by Riasalit** [comment]
> The CI actions need to all complete in order to let this through and currently they do not.

Merged develop into the branch, they now pass

**Pull request merged**
