### PR TITLE
Feature 88 notify dialog

### PR DESCRIPTION
**Pull request by msimon16**
Notify dialog is a widget that takes a title and a description, to notify the user of the given input. The user can confirm 'okay' with a button.

image

Testing that the notify dialog closes is missing.
Testing can be done but adds functionality to the code, solely for the use for testing (adds a bloc)

PR for Issue #88

### CODE REVIEW

**Comment by TobiasPalludan** [comment]
@aau-giraf/sw608f19 you have been assigned this. Here's your checklist. I marked @Hylet as the reviewer, but you might change it as you like.

Please use the following checklist. Feel free to check it off as you go along.

**Code Design**
- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [x] Could this code, to the best of your knowledge, have reused existing code?
- [x] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [x] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [x] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [x] Are the features that the code claims to implement, actually implemented?
- [x] Does it look like the code has bugs?
- [x] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [x] Are UI messages, that the user might meet, actually helpful?
- [x] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [x] Is there well written code in this? Remember to tell the developer!

**Comment by TobiasPalludan** [comment]
@aau-giraf/sw612f19 you have been assigned this. Here's your checklist. I marked @thomaslhansen as the reviewer, but you might change it as you like.

Please use the following checklist. Feel free to check it off as you go along.

**Code Design**
- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [x] Could this code, to the best of your knowledge, have reused existing code?
- [x] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [x] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [x] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [x] Are the features that the code claims to implement, actually implemented?
- [x] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [ ] Are UI messages, that the user might meet, actually helpful?
- [x] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [x] Is there well written code in this? Remember to tell the developer!

**Comment by Tekrus** [comment]
Is it possible to make the button gradient, as described in [the design guide](https://aau-giraf.github.io/wiki/design_guide/buttons.html)?

**Comment by msimon16** [comment]
> Is it possible to make the button gradient, as described in [the design guide](https://aau-giraf.github.io/wiki/design_guide/buttons.html)?

yes, but this is already made as an issue #85 , (to avoid duplication of code) 
I spoke with the group some time ago, and they are making the button with gradient colors. 
When that issue is done, this okay button should be replaced.

**Comment by Tekrus** [comment]
> 
> 
> > Is it possible to make the button gradient, as described in [the design guide](https://aau-giraf.github.io/wiki/design_guide/buttons.html)?
> 
> yes, but this is already made as an issue #85 , (to avoid duplication of code)
> I spoke with the group some time ago, and they are making the button with gradient colors.
> When that issue is done, this okay button should be replaced.

Awesome! Please remember to make an issue stating that this needs to be done, so that we don't forget.

**Review by thomaslhansen — APPROVED** [review]

**Review by Hylet — APPROVED** [review]

**Pull request merged**
