### PR TITLE
Issue 128

### PR DESCRIPTION
**Pull request by scarress**
Should be merged after #132 is merged
#128 
Oneliner for clearing the password input field after use.

### CODE REVIEW

**Review by Last16 — DISMISSED** [review]

**Comment by User12837985123** [comment]
Looks good :D But if you enter the password and close the dialog without changing mode, the password is still saved. This should probably be made as an another issue.

**Review by User12837985123 — DISMISSED** [review]

**Comment by Last16** [comment]
> Looks good :D But if you enter the password and close the dialog without changing mode, the password is still saved. This should probably be made as an another issue.

Happens both when using the X on the dialog and when using the back button on the device.

**Comment by Tekrus** [comment]
The group agreed to fix that it's not cleared when closing the dialog button right away, will approve whenever that's fixed 👍

**Comment by sipman** [comment]
The bug with clicking the 'x' and it still remembers the password should be fixed now.

We fixed it by instead of clearing the `TextEditingController`, we simply instanciates the controller in the onClick-closure, this is safe since it is inside a closure and there by as soon as that closure return ie, pops, it will be garbage collected.

**Review by Last16 — APPROVED** [review]
Works like a charm. 
However, I noticed that when entering the wrong password, no dialog is shown to inform the user that the password was wrong, it simply closes the dialog and nothing more. This is obviously not related to this issue, but kinda smells like a new issue @Moesgaarda

**Review by Tekrus — APPROVED** [review]

**Comment by Tekrus** [comment]
> 
> 
> Works like a charm.
> However, I noticed that when entering the wrong password, no dialog is shown to inform the user that the password was wrong, it simply closes the dialog and nothing more. This is obviously not related to this issue, but kinda smells like a new issue @Moesgaarda

This is now a new issue, nice catch!

**Review by User12837985123 — APPROVED** [review]

**Pull request merged**
