### PR TITLE
Feature 202

### LINKED ISSUE #202: As a guardian I would like to be able to edit weekplan details (name, picture) so that I can fix mistakes I made
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to change the name or image of a weekplan

**Describe the solution you'd like**
I would like to somehow get in to an edit menu of sorts where I can change the image and name of the weekplan

**Describe alternatives you've considered**
no

**Additional context**
null

### PR DESCRIPTION
**Pull request by MrPekar98**
fixes #202 
Pull request #357 tests editing a week plan.

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw607f20 you have been assigned this. Here's your checklist. 
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**

- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**

For this part, open the app, and test:

- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**

- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw611f20 you have been assigned this. Here's your checklist. 
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**

- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**

For this part, open the app, and test:

- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**

- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

**Review by EsbenNedergaard — CHANGES_REQUESTED** [review]
You do not really test the new edit_weekplan_screen, which is the new thing in the feature.

**Comment by MrPekar98** [comment]
@EsbenNedergaard That is because the test of edit_weekplan_screen.dart is added in PR 357 as I wrote in the comment.

**Comment by EsbenNedergaard** [comment]
> @EsbenNedergaard That is because the test of edit_weekplan_screen.dart is added in PR 357 as I wrote in the comment.

I just noticed i will apprive now

**Review by EsbenNedergaard — APPROVED** [review]

**Review by Badgie — APPROVED** [review]
Looks good :+1:

**Pull request merged**
