### PR TITLE
Feature/429.5

### LINKED ISSUE #429: As a guardian, I would like to know when I have written a wrong login fast
**Is your feature request related to a problem? Please describe.**
Currently when logging in, if I type a wrong username/password, I have to wait for 2 seconds until I get the response.
This is because instead of returning the `auth`-call response, a timer is set to 2000 ms. When that timer runs out, a lot of other things are tested before finally actually returning that the actual error was that the username/password combination was wrong.
Context:
https://github.com/aau-giraf/weekplanner/blob/b37bf396816e6592be1fb44f605759cc13d68b9e/lib/screens/login_screen.dart#L42-L55

**Describe the solution you'd like**
For the BLoC to return as soon as the response is ready.

**Additional context**
This was found when examining #349. In this issue, there is a code example on how the `listen` functionality could be used to react to the `ApiException` thrown by the api_client.

### PR DESCRIPTION
**Pull request by Emil7370**
Removed login delay on erroneous login

### CODE REVIEW

**Comment by Determinatoro** [comment]
Please use the following checklist, @Rosmarium. Feel free to check it off as you go along.

**Code Design** 

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [x] Has all the added code been properly commented

Only check one of the items below:

- [x] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Comment by Determinatoro** [comment]
Please use the following checklist, @ZohraAmini. Feel free to check it off as you go along.

**Code Design** 

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [ ] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [ ] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Comment by Rosmarium** [comment]
I think something went wrong with the merge? Some of the changes have nothing to do with the issue?

**Comment by Emil7370** [comment]
> I think something went wrong with the merge? Some of the changes have nothing to do with the issue?

Yes some of the changes are from a commit on the develop branch due to an error when trying to rebase.

The relevant changes are in lib/screens/login_screen.dart
The other changes have already been approved and it should have no impact on this merge

**Comment by Rosmarium** [comment]
> > I think something went wrong with the merge? Some of the changes have nothing to do with the issue?
> 
> Yes some of the changes are from a commit on the develop branch due to an error when trying to rebase.
> 
> The relevant changes are in lib/screens/login_screen.dart
> The other changes have already been approved and it should have no impact on this merge

Okay just making sure :) Thanks for clarifying.

**Review by Rosmarium — APPROVED** [review]

**Review by ZohraAmini — APPROVED** [review]

**Pull request merged**
