### PR TITLE
Feature/540: Collapse "overståede uger"

### LINKED ISSUE #540: As a guardian i would like to be able to hide or collapse "Overståede uger"
**Is your feature request related to a problem? Please describe.**
The "Overståede uger" takes up a lot of room on the weekplan selection screen, especially on landscape mode, so having the option to hide it would make the upcoming weekplans easier to navigate and select from.

**Describe the solution you'd like**
An ability to hide the "overståede uger" either with a button or a collapsible

### PR DESCRIPTION
**Pull request by Rosmarium**
You are now able to collapse "overståede uger"

A test has been implemented to check the buttons work as intended

Closes #540.

### CODE REVIEW

**Comment by Determinatoro** [comment]
Please use the following checklist, @Emil-Linnebjerg. Feel free to check it off as you go along.

**Code Design** 

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [x] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [x] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [x] All functionality is covered by tests
- [x] The tests has sensible names
- [x] By reading the tests you know what they cover
- [x] The tests cover sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Comment by Determinatoro** [comment]
Please use the following checklist, @ChristofferAaen. Feel free to check it off as you go along.

**Code Design** 

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [x] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [x] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [x] All functionality is covered by tests
- [x] The tests has sensible names
- [x] By reading the tests you know what they cover
- [x] The tests cover sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Review by Emil-Linnebjerg — DISMISSED** [review]

**Comment by Rosmarium** [comment]
@Emil-Linnebjerg Sorry. Har lige løst to konfikter, som opstod pga. andre branches var blevet merged. Så du er lige nødt til at godkende igen og @ChristofferAaen plz review.

**Comment by Rosmarium** [comment]
Der er pt. fejl, vi tænker, det er fordi, den er gjort stateful og kigger på en løsning

**Comment by ChristofferAaen** [comment]
I _pushEditWeekPlan functionen er _weekBlock undefined ved mig

**Comment by Rosmarium** [comment]
> I _pushEditWeekPlan functionen er _weekBlock undefined ved mig

Yup vi arbejder på det, se tidligere kommentarer :)

**Comment by Rosmarium** [comment]
@ChristofferAaen og @Emil-Linnebjerg det er nu fixed

**Comment by ChristofferAaen** [comment]
Det ser fint ud når man kører appen, dog når jeg kører testen så printer den 
Old weeks true
Old weeks false
hvilket, som jeg kan se, kommer fra funktionen på linje 46.
Vi skal ikke printe noget når vi kører test :)

**Comment by Rosmarium** [comment]
> Det ser fint ud når man kører appen, dog når jeg kører testen så printer den
> Old weeks true
> Old weeks false
> hvilket, som jeg kan se, kommer fra funktionen på linje 46.
> Vi skal ikke printe noget når vi kører test :)

Det er lige en print-debugger som er sluppet igennem :P den er fjernet nu.

**Review by ChristofferAaen — APPROVED** [review]

**Review by Emil-Linnebjerg — APPROVED** [review]

**Pull request merged**
