### PR TITLE
Added loading spinner to login screen

### PR DESCRIPTION
**Pull request by Tricky12321**
Added loading spinner to the login screen
Issue #137 

Screenshot_20190410-093909__01

### CODE REVIEW

**Comment by TobiasPalludan** [comment]
@aau-giraf/sw613f19 you have been assigned this. Here's your checklist. I marked @ralled96 as the reviewer, but you might change it as you like.

Please use the following checklist. Feel free to check it off as you go along.

**Code Design**
- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [x] Could this code, to the best of your knowledge, have reused existing code?
- [x] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [x] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [x] Do the tests cover sensible cases? Both happy paths and exception paths?
- [x] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [x] Are error messages in the code understandable?
- [x] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [x] Are the features that the code claims to implement, actually implemented?
- [x] Does it look like the code has bugs?
- [x] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [x] Are UI messages, that the user might meet, actually helpful?
- [x] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [x] Is there well written code in this? Remember to tell the developer!

**Comment by TobiasPalludan** [comment]
@aau-giraf/sw602f19 you have been assigned this. Here's your checklist. I marked @Jacob6565 as the reviewer, but you might change it as you like.

Please use the following checklist. Feel free to check it off as you go along.

**Code Design**
- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [x] Could this code, to the best of your knowledge, have reused existing code?
- [x] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [x] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [x] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [x] Are the features that the code claims to implement, actually implemented?
- [x] Does it look like the code has bugs?
- [x] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [x] Are UI messages, that the user might meet, actually helpful?
- [x] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [x] Is there well written code in this? Remember to tell the developer!

**Comment by ralled96** [comment]
The loading spinner works nicely, but there is no error message when the login fails, this should be implemented as #137 describes. We will review after this is implemented.

**Review by ralled96 — CHANGES_REQUESTED** [review]
The loading spinner works nicely, but there is no error message when the login fails, this should be implemented as #137 describes. We will review after this is implemented.

**Comment by Tricky12321** [comment]
> The loading spinner works nicely, but there is no error message when the login fails, this should be implemented as #137 describes. We will review after this is implemented.

This is another issue, #138 and relies on PR #139 before this can be implemented

**Review by ralled96 — APPROVED** [review]

**Review by ralled96 — CHANGES_REQUESTED** [review]
The code is well written and understandable, but there is no tests on the actual loading spinner.

**Comment by Tricky12321** [comment]
> The code is well written and understandable, but there is no tests on the actual loading spinner.

This is a known issue, there is no way to write tests for Dialogs. This has been discussed with the PO group. This has been posted to the flutter github page as a issue
[Link to issue](
https://github.com/aau-giraf/weekplanner/issues/108#issuecomment-481241802)

**Comment by User12837985123** [comment]
I also think the code is well written and understandable, and that the only things missing are tests.

**Comment by Tricky12321** [comment]
> I also think the code is well written and understandable, and that the only things missing are tests.

This is a known issue, there is no way to write tests for Dialogs. This has been discussed with the PO group. This has been posted to the flutter github page as a issue
[Link to issue](
https://github.com/aau-giraf/weekplanner/issues/108#issuecomment-481241802)

**Comment by User12837985123** [comment]
> 
> 
> > I also think the code is well written and understandable, and that the only things missing are tests.
> 
> This is a known issue, there is no way to write tests for Dialogs. This has been discussed with the PO group

I don't know if is it necessary or not, but can't you make some small tests just testing if the desired functions are called or not? It might be silly to do, but just wanted to put the idea on the table :)

**Comment by Tekrus** [comment]
Design is consistent with the design guide, so that part is PO approved. 👍 

I think it's a good point to test if the desired functions are called, as @Jacob6565 suggests.

**Comment by Tricky12321** [comment]
> > > I also think the code is well written and understandable, and that the only things missing are tests.
> > 
> > 
> > This is a known issue, there is no way to write tests for Dialogs. This has been discussed with the PO group
> 
> I don't know if is it necessary or not, but can't you make some small tests just testing if the desired functions are called or not? I might be silly to do, but just wanted to put the idea on the table :)

This is unfurturnately not possible, since how showDialog method (From flutter) it requires a context, which to my knowledge cannot be mocked

**Comment by Tricky12321** [comment]
There has been added some tests to the Loading spinner, using a completely mocked screen, inorder to get a context to show the Dialog on

**Review by ralled96 — APPROVED** [review]

**Review by User12837985123 — APPROVED** [review]

**Comment by TobiasPalludan** [comment]
@Tricky12321 please remember to delete branch, unless you will be adding more to it?

**Pull request merged**
