### PR TITLE
Fixes #387 and #386

### LINKED ISSUE #386: The list of week plans in WeekplansBloc is emitted for every single week plan
**Describe the bug**
The list of week plans in `WeekplansBloc` is emitted from `_weekModel` for every single week plan. This means the week plan selector screen is rendered once for every week plan. (First with 1 week plan, then with 2, and so on).

**To Reproduce**
1. Place a breakpoint on line 66 in `weekplan_selector_screen.dart`.
2. Start debugging the app and log in.
3. Click on a citizen. 
4. Observe the breakpoint being reached multiple times (if there are multiple week plans for the citizen).

**Expected behavior**
The breakpoint is reached 1 time, and the list of week plans is complete.

**Actual behavior**
The list is appended to and streamed for every week plan (almost; sometimes 2-3 week plans are added to the list simultaneously).

**Screenshots**
N/A

**Environment**
- OS: N/A
- Emulator: N/A
- Phone: N/A
- Release version: 2020S1R1 

**Additional context**
This issue is closely related to #387, and should be fixed by the same developer.

### LINKED ISSUE #387: Can't create new week plan, if citizen doesn't already have at least one
**Describe the bug**
When a citizen doesn't have an existing week plan, a guardian can't create a new one. This is caused by an error in the `getAllWeekInfo` method in `WeekplansBloc`. The list of week plans is only emitted from `_weekModel` if there is at least one week plan. 

**To Reproduce**
1. Run the app and log in as a guardian.
2. Click on a citizen. 
3. If there are any week plans, delete them all.
4. Go back to select a citizen screen and click on the same citizen. 
5. Try to create a new week plan.
6. When pressing "Gem ugeplan", nothing happens.

**Expected behavior**
The new week plan is created.

**Actual behavior**
Nothing happens.

**Screenshots**
N/A

**Environment**
- OS: N/A
- Emulator: N/A
- Phone: N/A
- Release version: 2020S1R1 

**Additional context**
This issue is closely related to #386, and should be fixed by the same developer.

### PR DESCRIPTION
**Pull request by giano574**
Fixes #387 and fixes #386.
- Created two tests that failed before fixing #387.

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw609f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by T-Dawq — COMMENTED** [review]
You say that the implementation is a "hack". What would be the proper way and how do we make it possible? Have issues been created to handle this?

Are you sure that these changes should be merged into master?

**Comment by giano574** [comment]
> You say that the implementation is a "hack". What would be the proper way and how do we make it possible? Have issues been created to handle this?

I say that the existing solution is a hack. I didn't change that, because it would require the API to be changed. And yes, I will create an issue about that. 

I consider it a hack, because if the citizen has 0 existing week plans, the REST API returns 
```
{
  "success": false,
  "errorKey": "NoWeekScheduleFound"
}
```
thus making the API Client return an error.

> Are you sure that these changes should be merged into master?

I think they should since the app is broken without the fix.

**Comment by Lortemanden** [comment]
> Are you sure that these changes should be merged into master?

> I think they should since the app is broken without the fix.

Should they also not be merged into develop? Else the app is going to be broken next time we do a release?

**Comment by giano574** [comment]
> > Are you sure that these changes should be merged into master?
> 
> > I think they should since the app is broken without the fix.
> 
> Should they also not be merged into develop? Else the app is going to be broken next time we do a release?

Yes, they will be merged into `develop` by the process group.
> Mathias - mandr17 Today at 09:23
> @​Robin Ezra - rezra15 Vi sætter reviewers på, og sørger for at merge den tilbage ind i develop når den er merged.

**Review by Vino98 — APPROVED** [review]

**Comment by giano574** [comment]
Fixed minor bug where `getAllWeekInfo` was called twice when an error occured (`onError`). Now it is only called once.

**Review by Vino98 — APPROVED** [review]

**Review by Lortemanden — APPROVED** [review]

**Pull request merged**
