### PR TITLE
Fix 492

### LINKED ISSUE #492: Pictogram text is still shown on completed activities in citizen mode.
**Describe the bug**
When the option "Fjern aktivitet fra borgeren" has been selected, the text on pictograms are still shown on completed activities.

**To Reproduce**
1. Go to user setting.
2. Choose "Fjern aktivitet fra borgeren" in the "Tegn for udførelse" section.
3. Go to a week plan that has completed activities and enter citizen mode.
4. See that the completed activities still have pictogram text beneath.

**Expected behavior**
The pictogram text is not shown.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ssrika17**
Fixes #492

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw608f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [x] The tests covers sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [x] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [x] There is well written code in this. Remember to tell the developer!

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw616f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by MrPekar98 — DISMISSED** [review]

**Review by MrPekar98 — DISMISSED** [review]

**Comment by tuanvu29** [comment]
image

Der bliver et tomt mellemrum for færdige aktiviteter, er det meningen, burde den ikke bare lade være med at gøre plads til færdige aktiviteter?

**Comment by ssrika17** [comment]
> image
> 
> Der bliver et tomt mellemrum for færdige aktiviteter, er det meningen, burde den ikke bare lade være med at gøre plads til færdige aktiviteter?

It might be true that the empty space is not intended. However, the bug is not directly related to this issue as this issue only deals with the pictogram texts. As far as I can see, the bug you describe is related to and is caused by activities that are removed. I have created a new issue for this bug:  https://github.com/aau-giraf/weekplanner/issues/525

**Comment by ssrika17** [comment]
It has been clarified by the PO group that the empty space is actually wanted by the customers

**Comment by tuanvu29** [comment]
> It has been clarified by the PO group that the empty space is actually wanted by the customers

I see, but the empty space should be as large as an activity with text. Right now the empty space is equivelent with an activity without text, which offsets the activities of that day compared to the others.

**Comment by ssrika17** [comment]
> > It has been clarified by the PO group that the empty space is actually wanted by the customers
> 
> I see, but the empty space should be as large as an activity with text. Right now the empty space is equivelent with an activity without text, which offsets the activities of that day compared to the others.

This is now fixed

**Comment by tuanvu29** [comment]
Yes it seems to be fixed, but when I'm reordering some of the activities in the weekplanScreen, all of the activities "dissapears" before reloading back, which doesn't happen on the develop branch. Can't seem to find the code in the implementation that might cause this.

**Comment by EsbenNedergaard** [comment]
> Yes it seems to be fixed, but when I'm reordering some of the activities in the weekplanScreen, all of the activities "dissapears" before reloading back, which doesn't happen on the develop branch. Can't seem to find the code in the implementation that might cause this.

This happens because we now need to load the settings and whether we are in citizen or guardian mode before rendering the activities, because we need to determine if the opacity of the activity should be 0.0 or 1.0. I will try and see if i can move some of these loads a bit down agian.

**Comment by ssrika17** [comment]
> Yes it seems to be fixed, but when I'm reordering some of the activities in the weekplanScreen, all of the activities "dissapears" before reloading back, which doesn't happen on the develop branch. Can't seem to find the code in the implementation that might cause this.

It should be fixed now

**Review by tuanvu29 — APPROVED** [review]
Looks good

**Review by MrPekar98 — APPROVED** [review]

**Pull request merged**
