### PR TITLE
Feature/134 Adding pictogram pictures with camera 

### LINKED ISSUE #134: As a guardian, I would like a way to add pictograms by taking a picture from my camera so that I can quickly improvise if the system does not have the activity I want

### PR DESCRIPTION
**Pull request by ggAlexS**
Closes #134 adding pictogram pictures can now be added from the camera

### CODE REVIEW

**Comment by Determinatoro** [comment]
Please use the following checklist, @AdrianPlesner . Feel free to check it off as you go along.

**Assets**
- [x] The ``environments.json`` file has the following default values:
```
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}
```

**Code Design** 

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [x] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [x] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Comment by Determinatoro** [comment]
Please use the following checklist, @ChristofferAaen. Feel free to check it off as you go along.

**Assets**
- [x] The ``environments.json`` file has the following default values:
```
{
  "SERVER_HOST": "https://srv.giraf.cs.aau.dk/DEV/API",
  "DEBUG": true,
  "USERNAME": "Graatand",
  "PASSWORD": "password"
}
```

**Code Design** 

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems     
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code does not introduce functionality that is unnecessary for solving the problem

**Code Readability** 

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no \"hack\", or obscure solution   

**Code Maintainability**

- [x] Has all the added code been properly commented

Only check one of the items below:

- [ ] The functionality does **not** need to be covered by tests
- [x] The functionality needs to be covered by tests

Only check these if the functionality needs to be covered by tests:

- [ ] All functionality is covered by tests
- [ ] The tests has sensible names
- [ ] By reading the tests you know what they cover
- [ ] The tests cover sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing

**Functionality**

For this part, open the app, and test:
- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Comment by ChristofferAaen** [comment]
Er det meningen at jeres pubspec.lock fil skal med i committet?

**Comment by ChristofferAaen** [comment]
og i har 10 tests som fejler

**Comment by LivHolm** [comment]
@ChristofferAaen øh er der en grund til at den her pull request er blevet lukket før sprint review?

**Comment by ChristofferAaen** [comment]
okay i see im here

**Comment by AdrianPlesner** [comment]
I am here

**Review by AdrianPlesner — CHANGES_REQUESTED** [review]
Det ser jo meget fint ud, men der er ikke nogle tests?

**Comment by JeppeKLau** [comment]
> 
> 
> Det ser jo meget fint ud, men der er ikke nogle tests?

Det er integreret præcis på den samme måde som når man henter billeder gennem galleriet, så er derfor heller ikke testet.
Besides, funktionaliteten er der så den skal bare merges.

**Comment by AdrianPlesner** [comment]
> > Det ser jo meget fint ud, men der er ikke nogle tests?
> 
> Det er integreret præcis på den samme måde som når man henter billeder gennem galleriet, så er derfor heller ikke testet.
> Besides, funktionaliteten er der så den skal bare merges.

Det at andre ikke har lavet test er vel ikke et argument for at du ikke skal gøre det, desuden kunne man da som minimum lave widget test på den skærm der er lavet, hvilket desuden er gjort med upload_image_from_phone_screen, omend ikke så grundigt som man kunne forestille sig. 

upload_from_gallery_bloc og upload_image_from_phone_screen er blot en lille del af dette projekt der mangler sørgeligt meget test, men det er ingen begrundelse for ikke at teste ny funktionalitet.

**Comment by JeppeKLau** [comment]
> 
> 
> > > Det ser jo meget fint ud, men der er ikke nogle tests?
> > 
> > 
> > Det er integreret præcis på den samme måde som når man henter billeder gennem galleriet, så er derfor heller ikke testet.
> > Besides, funktionaliteten er der så den skal bare merges.
> 
> Det at andre ikke har lavet test er vel ikke et argument for at du ikke skal gøre det, desuden kunne man da som minimum lave widget test på den skærm der er lavet, hvilket desuden er gjort med upload_image_from_phone_screen, omend ikke så grundigt som man kunne forestille sig.
> 
> upload_from_gallery_bloc og upload_image_from_phone_screen er blot en lille del af dette projekt der mangler sørgeligt meget test, men det er ingen begrundelse for ikke at teste ny funktionalitet.

Men det at andre har lavet dårlig kode er nok undskyldning for selv at gøre det? Synes det er lidt dobbelt moralsk det du skriver der.
Og hvorfor er det ikke @Huften der reviewer? Hvorfor har du overtaget den her?

**Comment by AdrianPlesner** [comment]
> Og hvorfor er det ikke @Huften der reviewer? Hvorfor har du overtaget den her?

Det forholder sig sådan at @Huften desværre er syg og derfor har jeg overtaget da det haster at få reviewet de sidste pull requests. Det har desuden intet med noget at gøre, enhver kan se at der er 0 test i denne pull request, hvilket ikke er godt nok uden en megt god grund? Desuden har du selv overtager flere reviews fra @13uller så jeg kan slet ikke se hvor den kommentar kommer fra.

**Comment by JeppeKLau** [comment]
> 
> 
> > Og hvorfor er det ikke @Huften der reviewer? Hvorfor har du overtaget den her?
> 
> Det forholder sig sådan at @Huften desværre er syg og derfor har jeg overtaget da det haster at få reviewet de sidste pull requests. Det har desuden intet med noget at gøre, enhver kan se at der er 0 test i denne pull request, hvilket ikke er godt nok uden en megt god grund? Desuden har du selv overtager flere reviews fra @13uller så jeg kan slet ikke se hvor den kommentar kommer fra.

Grundlaget for at det ikke er testet er at koden er den samme som til gallery pickeren, som heller ikke er testet.

**Review by AdrianPlesner — APPROVED** [review]

**Review by ChristofferAaen — APPROVED** [review]

**Pull request merged**
