### PR TITLE
Feature 052 - add an activity

### LINKED ISSUE #52: As a guardian I would like to be able to add a new activity on a citizens week plan so that it fits their schedule
Tasks: 

- [ ] Make a Pictogram search widget (or if one exists, use it)
- [ ] Make a BLoC that should have the responsibility of adding a activity(Pictogram) to a weekday, remember that a weekday belongs to a citizen. This BLoC could have both the obligation to send the http request to the web-api and stream the result to a listener.
- [ ] Make the weekplan-screen allow for the click on the plus button. (This might requirer a BLoC in order to keep track of state)

This story is blocked by #46

### PR DESCRIPTION
**Pull request by TobiasPalludan**
This closes #52.

57015655_323446054967908_750115707533918208_n

### CODE REVIEW

**Comment by TobiasPalludan** [comment]
@aau-giraf/sw608f19 you have been assigned this. Here's your checklist. I marked @ChristianBroS as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [x] Could this code, to the best of your knowledge, have reused existing code?
- [x] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [x] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [x] Do the tests cover sensible cases? Both happy paths and exception paths?
- [x] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [x] Are error messages in the code understandable?
- [x] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [x] Are the features that the code claims to implement, actually implemented?
- [x] Does it look like the code has bugs?
- [x] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [x] Are UI messages, that the user might meet, actually helpful?
- [x] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [x] Is there well written code in this? Remember to tell the developer!

**Comment by TobiasPalludan** [comment]
@aau-giraf/sw612f19 you have been assigned this. Here's your checklist. I marked @thomaslhansen as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [x] Could this code, to the best of your knowledge, have reused existing code?
- [x] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [x] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [x] Do the tests cover sensible cases? Both happy paths and exception paths?
- [x] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [x] Are error messages in the code understandable?
- [x] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [x] Are the features that the code claims to implement, actually implemented?
- [x] Does it look like the code has bugs?
- [x] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [x] Are UI messages, that the user might meet, actually helpful?
- [x] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [x] Is there well written code in this? Remember to tell the developer!

**Review by ChristianBroS — COMMENTED** [review]
When adding an activity to a citizens weekplan it is not saved to the database. This means that when you log out, the changes are lost. Is this intentional?

**Review by ChristianBroS — CHANGES_REQUESTED** [review]
The following files should be deleted:
lib/models/user_week_model.dart
lib/providers/api/user_api.dart
test/models/user_week_model_test.dart

This is because the api has been moved to it's own repository. 
Otherwise, good work :DDD

**Comment by TobiasPalludan** [comment]
@ChristianBroS thank you. I deleted the user_api, but not the files for the user_week. The user_week is not part of the API, but a helper function we have introduced for this functionality, wrapping a user and a week. Because of that it does not make sense to expose it to other potential users of the API :)

**Review by ChristianBroS — APPROVED** [review]

**Review by thomaslhansen — APPROVED** [review]

**Review by Tekrus — APPROVED** [review]
Design godkendt

**Pull request merged**
