### PR TITLE
fixed pubspec + info errors

### PR DESCRIPTION
**Pull request by Lildhansen**
fixed the info errors with lines being longer than 80 chars + an unused import
also fixed the pubspec.lock

### CODE REVIEW

**Comment by Lildhansen** [comment]
image
These tests fails still, though i am not sure why, since all tests passed when working on it friday, but now they fail, and my changes should have no effect on these anyway

**Comment by Lildhansen** [comment]
Also on github actions only the 2 tests in the weekplan_screen_test fails - not the show_activity_screen_test

**Comment by andreaslborg** [comment]
```
Analyzing weekplanner...                                        

   info • Duplicate import • lib/screens/settings_screens/settings_screen.dart:30:8 • duplicate_import
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:63:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:86:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:93:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:100:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:107:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:1[14](https://github.com/aau-giraf/weekplanner/actions/runs/3618685866/jobs/6098833855#step:9:15):81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:121:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:128:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:135:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:142:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:149:81 • lines_longer_than_80_chars
   info • Avoid lines longer than 80 characters • test/screens/settings_screens/number_of_days_selection_screen.dart:[15](https://github.com/aau-giraf/weekplanner/actions/runs/3618685866/jobs/6098833855#step:9:16)6:81 • lines_longer_than_80_chars

13 issues found. (ran in [27](https://github.com/aau-giraf/weekplanner/actions/runs/3618685866/jobs/6098833855#step:9:28).4s)
Error: Process completed with exit code 1.
```

**Comment by andreaslborg** [comment]
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown while running async test code:
Expected: exactly one matching node in the widget tree
  Actual: _KeyFinder:<zero widgets with key [<'TimerInitKey'>] (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _expect (package:test_api/src/expect/expect.dart:129:3)
#2      expect (package:test_api/src/expect/expect.dart:46:3)
#3      expect (package:flutter_test/src/widget_tester.dart:460:16)
#4      main.<anonymous closure>.<anonymous closure> (file:///home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart:1187:9)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

01:42 +345 -1: /home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart: Aciticy card starts time when activated and shows it for citizen [E]                                  
  Test failed. See exception logs above.
  The test description was: Aciticy card starts time when activated and shows it for citizen
  

To run this test again: /opt/hostedtoolcache/flutter/3.3.8-stable/x64/bin/cache/dart-sdk/bin/dart test /home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart -p vm --plain-name 'Aciticy card starts time when activated and shows it for citizen'

01:42 +345 -1: /home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart: Aciticy card has completed icon when activity is completed                                            
01:42 +346 -1: /home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart: Aciticy card has completed icon when activity is completed                                            
01:42 +346 -1: /home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart: click actitivty card for citizen does nothing if the activity is completed or the timer is running    
01:42 +346 -1: /home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart: click actitivty card for citizen does nothing if the activity is completed or the timer is running    
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown while running async test code:
Expected: exactly one matching node in the widget tree
  Actual: _KeyFinder:<zero widgets with key [<'TimerInitKey'>] (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/expect/expect.dart:134:31)
#1      _expect (package:test_api/src/expect/expect.dart:129:3)
#2      expect (package:test_api/src/expect/expect.dart:46:3)
#3      expect (package:flutter_test/src/widget_tester.dart:460:16)
#4      main.<anonymous closure>.<anonymous closure> (file:///home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart:1235:9)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════

01:42 +346 -2: /home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart: click actitivty card for citizen does nothing if the activity is completed or the timer is running [E]
  Test failed. See exception logs above.
  The test description was: click actitivty card for citizen does nothing if the activity is completed or the timer is running
  

To run this test again: /opt/hostedtoolcache/flutter/3.3.8-stable/x64/bin/cache/dart-sdk/bin/dart test /home/runner/work/weekplanner/weekplanner/test/screens/weekplan_screen_test.dart -p vm --plain-name 'click actitivty card for citizen does nothing if the activity is completed or the timer is running'

```

**Review by andreaslborg — CHANGES_REQUESTED** [review]
Fix tests or revert the PR that broke develop.

**Review by andreaslborg — APPROVED** [review]
Tests passes now

**Review by malgreen — APPROVED** [review]
LGTM (if not monday)

**Pull request merged**
