### PR TITLE
Feature 221

### LINKED ISSUE #221: As a guardian I would like to be able to lock a citizens timer so that they can not pause or stop them once they are started.
**Is your feature request related to a problem? Please describe.**
Some citizen can't manage having control over the timer and will stop or reset it so they never would get the activity done.
**Describe the solution you'd like**
There should be a option to lock the timer for the citizen in the setting screen as shown below with the "Lås tidsstyring" button. 
image
 
When the timer is locked the citizen should see the following if there is a set timer that has not been started. The citizen should still be able to start the timer. 
image

When the timer starts the button should disappear as shown below.
image

The button should not return even when the timer is finished. 
image

**Additional context**
Some of the other settings shown in the settings screen might not have been implemented. That is not a part of this issue.

### PR DESCRIPTION
**Pull request by tuanvu29**
resolves #221 
To test the features implemented the web api(from develop branch) have to run locally and the line "ref: develop" needed to be added to the pupspec.yaml in weekplanner.  
image
This needs to be done, since the changes to the web-api and api client, linked to in issue #221, is on develop branches and have not yet been merge to the master branches. 
*This also results in that some of the GitHub Actions fails*

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw613f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw614f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by Lortemanden — CHANGES_REQUESTED** [review]
The citizen it's not able to mark the activity as completed once the timer is completed. This is possible if the citizen does it before the timer stops or goes out of the activity and then back in. 
I can see the same thing happens when the locked timer setting is turned off, so it might not be caused by your implementation.

**Comment by tuanvu29** [comment]
> The citizen it's not able to mark the activity as completed once the timer is completed. This is possible if the citizen does it before the timer stops or goes out of the activity and then back in.
> I can see the same thing happens when the locked timer setting is turned off, so it might not be caused by your implementation.

We can still mark the activity as completed once the timer is completed. But we found an other error that might be related, which is when you are in an activity with a timer and you mark the activity as completed and uncheck it again. The activity will then dissapear/be deleted from the weekplan screen.
This bug is already on the develop branch.

**Review by Lortemanden — DISMISSED** [review]

**Review by mads-bo — APPROVED** [review]

**Review by dtidemann — APPROVED** [review]

**Pull request merged**
