### PR TITLE
Feature 270

### LINKED ISSUE #270: As a citizen I would like an indicator on my weekplan to show that an activity has a timer so that I know it beforehand
**Is your feature request related to a problem? Please describe.**
It should be visible from the weekplan, if an activity has a timer.

**Describe the solution you'd like**
If an activity has a timer, there should be an icon on it as shown in the prototype below. The icon is meant to mimic how the timer actually looks but not how far along it is, so the icon should be static.

**Describe alternatives you've considered**

**Additional context**
Weekplanner - Guardian - View weekplan - Timer indicator

### PR DESCRIPTION
**Pull request by MrPekar98**
fixes #270

### CODE REVIEW

**Comment by Lortemanden** [comment]
The indicator used is not the same as the one from the prototype. Can it be changed to the one from the prototype?

**Comment by MrPekar98** [comment]
@Lortemanden We don't have the icon file used in the prototype. It's also quite problematic to add custom icons.

**Comment by ceciliehyrup1** [comment]
@Lortemanden  https://api.flutter.dev/flutter/material/Icons-class.html it could be nice if one of these icons could work, if you think the one right now does not fit. 

Custom icons are not easy to work with, however if you think it is necessary to look more into, we will try again.

**Comment by Lortemanden** [comment]
We asked the customer if they wanted icons but they said no. They really wanted the indicator to match the timer in the activity. So if we could add a custom indicator it would be super nice. We got the icon from the prototype, but we haven't uploaded it to the wiki yet. So I am going to send it to you via discord, since I cant attach svg files to comments on github. 

Just so you are aware a lot of custom icons are used in the application. A list of the icons can be seen in the wiki. https://aau-giraf.github.io/wiki/development/design_guide/icons/

**Review by aerlingsson — APPROVED** [review]

**Review by Lortemanden — APPROVED** [review]

**Pull request merged**
