### PR TITLE
Restarts the weekday counter to show mon-fri even after changing orientation

### LINKED ISSUE #517: Random days are shown in mon-fri view for citizen
**Describe the bug**
If the option monday to friday are chosen in settings, random days are shown for the citizen.

**To Reproduce**
1. Set the Antal dage setting to Vis mandag til fredag.
2. Go back and switch to citizen mode
3. Try to change orientation.

**Expected behavior**
I expected that the days monday to friday are shown like before I change the orientation

**Actual behavior**
A clear and concise description of what actually happened.
Random days are shown.

**Screenshots**
Before change of orientation:
Screenshot_1589113977

After change of orientation:
Screenshot_1589114026

**Environment (please complete the following information):**
- OS: Android
- Emulator: Yes :D

### PR DESCRIPTION
**Pull request by Simon97**
fixes #517

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw615f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw616f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by giano574 — CHANGES_REQUESTED** [review]
The added line of code should be placed above the if statement on line 294. Otherwise we will not show the correct day when displaying a single day.

**Review by jbjarn17 — DISMISSED** [review]

**Comment by Simon97** [comment]
> The added line of code should be placed above the if statement on line 294. Otherwise we will not show the correct day when displaying a single day.

I will move it

**Review by jbjarn17 — APPROVED** [review]

**Review by giano574 — APPROVED** [review]

**Pull request merged**
