### PR TITLE
Logged in citizen skips choose citizen screen and are presented with the week plan selection screen - Feature/888v3

### LINKED ISSUE #888: As a citizen, I should skip the choose citizen screen ("vælg borger") and be presented with the week plan selection screen instead
## Description
Currently, when logging in as a citizen, you are presented with the screen for choosing a citizen ("vælg borger"). However, a citizen should not have this choice, but only be able to view their week plans.

Thus, a solution should contain the following:
- The screen for choosing a citizen should be skipped, such that when a citizen logs in, they are directly presented with an overview of their week plans.

### PR DESCRIPTION
**Pull request by andreasalstrup**
# Description

When a citizen is logged in; the week plan selection screen for that citizen will be displayed.
When any other user is logged in; the choose citizen screen will be displayed.

To solve this issue, `AuthBloc` stores the logged-in user data in a `GirafUserModel` object. Hence, the `loggedInUser` object in `auth_bloc.dart` is used to provide logged-in user data in `weekplan_selector_screen.dart` and `choose_citizen_screen.dart`.

Fixes #888 

## Type of change
- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tests has been updated to support this new feature.

**Development Configuration**

* Flutter version: 3.3.8
* Dart version: 2.18.4

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas, if necessary
- [X] I have made corresponding changes to the documentation, if necessary
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, if necessary
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [X] I have Acceptance Tested this on an Android device

### CODE REVIEW

**Review by andreaslborg — CHANGES_REQUESTED** [review]
Missing "Tilbage-knap" when logged in as a citizen and a week plan is opened.

image

**Comment by andreasalstrup** [comment]
> Missing "Tilbage-knap" when logged in as a citizen and a week plan is opened.
> 

Fixed!

**Comment by andreaslborg** [comment]
> > Missing "Tilbage-knap" when logged in as a citizen and a week plan is opened.
> 
> Fixed!

Fedt! Mangler bare lige at løse en file conflict, så er den klar!

**Review by ltranu20 — DISMISSED** [review]

**Comment by andreasalstrup** [comment]
> > > Missing "Tilbage-knap" when logged in as a citizen and a week plan is opened.
> > 
> > 
> > Fixed!
> 
> Fedt! Mangler bare lige at løse en file conflict, så er den klar!



> > > Missing "Tilbage-knap" when logged in as a citizen and a week plan is opened.
> > 
> > 
> > Fixed!
> 
> Fedt! Mangler bare lige at løse en file conflict, så er den klar!

Done!

**Review by andreaslborg — DISMISSED** [review]
Godt arbejde, lgtm

**Review by andreaslborg — DISMISSED** [review]

**Review by ltranu20 — DISMISSED** [review]

**Comment by andreaslborg** [comment]
Hvad sker der lige med tests nu? 😅

**Comment by andreasalstrup** [comment]
> Hvad sker der lige med tests nu? sweat_smile

🙏 develop branch

**Review by ltranu20 — APPROVED** [review]

**Review by andreaslborg — APPROVED** [review]

**Pull request merged**
