### PR TITLE
Create popup instead of disable button, when less or more than 1 week…

### LINKED ISSUE #539: Edit, copy and delete button have inconsistent behaviour on week plan selector screen
**Describe the bug**
The "Redigér" and "Slet" button have popups describing that you have to select at least one week plan, if none are selected.
The "Kopiér" button is just disabled until at least one week plan is selected. 

**To Reproduce**
1. Go to week plan selector screen.
2. Press the edit icon in the top right.
3. Press "Redigér", "Kopier", and "Slet" and observe the difference in behaviour.

**Expected behavior**
All buttons should produce popups.

**Actual behavior**
Described in "Describe the bug"

**Screenshots**
N/A

**Environment (please complete the following information):**
- OS: N/A
- Emulator: N/A
- Phone: N/A
- APK Version: N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by pegede17**
…plan is selected

fixes #539

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw615f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [x] The code is in the right place? (Both in terms of folder structure and class structure)
- [x] This code could not, to the best of my knowledge, have reused existing code
- [x] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [x] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [x] Names are meaningful and self-documenting
- [x] It is understandable, by reading the code, what it does
- [x] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [x] All new functionality is covered by tests
- [x] It is understandable, by reading the tests, what they do
- [x] The tests covers sensible cases. Both happy paths and exception paths
- [x] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [x] Error messages in the code are understandable
- [x] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [x] The features that the code claims to implement, are actually implemented
- [x] The code does not look like it has bugs
- [x] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [x] UI messages, that the user might meet, are actually helpful
- [x] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [x] There is well written code in this. Remember to tell the developer!

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw617f20 you have been assigned this. Here's your checklist.
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] The code is in the right place? (Both in terms of folder structure and class structure)
- [ ] This code could not, to the best of my knowledge, have reused existing code
- [ ] The code is not over-engineered. Examples of over-engineering: Implemented behavior for future problems
- [ ] The code does it introduce functionality that is not necessary for solving the problem

**Code Readability and Maintainability**

- [ ] Names are meaningful and self-documenting
- [ ] It is understandable, by reading the code, what it does
- [ ] The code is simple and readable. i.e. it contains no "hack", or obscure solution
- [ ] All new functionality is covered by tests
- [ ] It is understandable, by reading the tests, what they do
- [ ] The tests covers sensible cases. Both happy paths and exception paths
- [ ] The tests cover the full functionality. i.e., The tests fails if some of the requested functionality is missing
- [ ] Error messages in the code are understandable
- [ ] Confusing sections of code are covered by comments

**Functionality**

For this part, open the app, and test:

- [ ] The features that the code claims to implement, are actually implemented
- [ ] The code does not look like it has bugs
- [ ] All the new screens are reachable through in-app navigation

**Points for Discussion and Reflection**

- [ ] UI messages, that the user might meet, are actually helpful
- [ ] There are no errors that are bad practice. E.g. hard-coding a test database connection
- [ ] There is well written code in this. Remember to tell the developer!

**Review by Torpstitution — CHANGES_REQUESTED** [review]
Sådan som jeg forstår det, så skulle det være meningen at der kommer et popup når man trykker på knapperne, selv når ingen aktivitet er markeret? Dog kan jeg ikke lige få den til at vise popups, når ingen aktivitet er markeret?

**Comment by pegede17** [comment]
> Sådan som jeg forstår det, så skulle det være meningen at der kommer et popup når man trykker på knapperne, selv når ingen aktivitet er markeret? Dog kan jeg ikke lige få den til at vise popups, når ingen aktivitet er markeret?

Fixet er i forhold til kopiering af hele ugeplaner og ikke aktiviteter. Det var inkonsistent, i forhold til ugeplanerne, men aktivitererne er alle deaktiverede.

**Review by Torpstitution — APPROVED** [review]

**Review by Rsvend17 — APPROVED** [review]

**Pull request merged**
