### PR TITLE
Feature 323 - redesign of settings screen

### LINKED ISSUE #323: As a guardian I would like a settings function so that i can edit the standard settings for a specific citizen
**Is your feature request related to a problem? Please describe.**
It is important for the guardians to edit how a weekplan is shown to each individual citizen (e.g colors and number of days)

**Describe the solution you'd like**
A settings icon in the top right that gives acces to a settings menu as shown in the prototypes. The settings icon should becom available after a citizen has been selected. It is not part of the issue to add functionality to the buttons in the settings menu.

### PR DESCRIPTION
**Pull request by tdybda17**
closes #323

### CODE REVIEW

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw616f20 you have been assigned this. Here's your checklist. 
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**

- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**

For this part, open the app, and test:

- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**

- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

**Review by mads-bo — COMMENTED** [review]
@aau-giraf/sw617f20 you have been assigned this. Here's your checklist. 
Please use the following checklist. Feel free to check it off as you go along.

**Code Design**

- [ ] Is the code in the right place? (Both in terms of folder structure and class structure)
- [ ] Could this code, to the best of your knowledge, have reused existing code?
- [ ] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [ ] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**

- [ ] Are names meaningful and self-documenting?
- [ ] Is it understandable, by reading the code, what it does?
- [ ] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [ ] Is it understandable, by reading the tests, what they do?
- [ ] Do the tests cover sensible cases? Both happy paths and exception paths?
- [ ] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [ ] Are error messages in the code understandable?
- [ ] Are confusing sections of code covered by comments?

**Functionality**

For this part, open the app, and test:

- [ ] Are the features that the code claims to implement, actually implemented?
- [ ] Does it look like the code has bugs?
- [ ] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**

- [ ] Are UI messages, that the user might meet, actually helpful?
- [ ] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [ ] Is there well written code in this? Remember to tell the developer!

**Review by Semicolon1071 — DISMISSED** [review]

**Review by ThomasMG — CHANGES_REQUESTED** [review]
Jeg kan se at jeres `_button` metode producere en widget der minder meget om en `ListTile`, bortset fra at den også har en outline. Dette gør at når flere af sådanne ligger efter hinanden i listen, så vil linjerne imellem knapperne være tegnet dobbelt. Dette er synligt, især fordi ikke alle elementer er tegnet sådan.

Jeg foreslår at I stedet laver alle elementer som `ListTiles` eller `CheckboxListTile` og så bruger metoden `divideTiles()`, der automatisk laver linjer imellem elementer i listen.

**Review by Semicolon1071 — DISMISSED** [review]

**Review by ThomasMG — CHANGES_REQUESTED** [review]
There is still a lot of redundant code.
The `SizedBox`'es are the same except for their actual text, the dividers are written for each and every element. The `ListTile`'s are also identical except for actual text.  The `_button` method with is much more complicated than a simple `ListTile` with `onTap`.

Also the "titles" in the prototype has a grey background.

The code would be much more readable, if you defined simple methods for the different types of elements, and used them instead. This would also make it much easier to add new settings and functionality in the future.

**Review by Semicolon1071 — DISMISSED** [review]
Nu har jeg ikke mulighed for at teste til iOS, så ved ikke om det giver problemer, men der er checket følgende ind, som måske ikke skulle være checket ind? Det er filen " ios/Flutter/flutter_export_environment.sh" hvori der står "# This is a generated file; do not edit or check into version control."
Men jeg kan som sagt ikke teste om det skaber problemer (eller overhovedet er relevant). Det ser ud til at virke på Android, så approver.

**Comment by tdybda17** [comment]
> Nu har jeg ikke mulighed for at teste til iOS, så ved ikke om det giver problemer, men der er checket følgende ind, som måske ikke skulle være checket ind? Det er filen " ios/Flutter/flutter_export_environment.sh" hvori der står "# This is a generated file; do not edit or check into version control."
> Men jeg kan som sagt ikke teste om det skaber problemer (eller overhovedet er relevant). Det ser ud til at virke på Android, så approver.

Så hut jeg visker, så er gitignore filen på masteren blevet opdateret så de ikke ryger med. Der er bare ikke nogen som har opdateret develop branchen's gitignore

**Comment by giano574** [comment]
> Så hut jeg visker, så er gitignore filen på masteren blevet opdateret så de ikke ryger med. Der er bare ikke nogen som har opdateret develop branchen's gitignore

Hvis I merger uden at fjerne filen, så kommer den med ind i masteren, fordi den her branch tracker filen

**Review by ThomasMG — CHANGES_REQUESTED** [review]
Løsningen ser fin ud, men i mangler tests også.

**Review by ThomasMG — APPROVED** [review]

**Review by Semicolon1071 — APPROVED** [review]

**Pull request merged**
