### PR TITLE
Feature/696

### PR DESCRIPTION
**Pull request by emilnormann**
# Description

Fixes #\696 by reloading the screen after pressing a button. This is not optimal since it flashes but after trying everything we could think of to make a better solution and nothing working this is a working fix.

## Type of change

*Please delete options that are not relevant.*

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

No unit tests has been set up since every value is the same as before except the screen is updated correctly.

It has been checked that both accept and cancel correctly disables the other button and every other functionality on the screen still works.

**Development Configuration**
Set up after guide

# Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation, if necessary
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works, if necessary
- [ X] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device.

### CODE REVIEW

**Review by JJTM20 — DISMISSED** [review]
Lgtm+, works like a charm:)

**Review by mikejensen0 — CHANGES_REQUESTED** [review]
The fix itself works, but the unit tests needs to be adjusted. Some of the unit tests start failing, because there is an overflow of the RenderFlex class (see actions or run coverage tests locally).

**Review by mikejensen0 — APPROVED** [review]
lgtm

**Comment by miniJmo** [comment]
lgtm :shipit:

**Review by miniJmo — APPROVED** [review]
lgtm :shipit:

**Pull request merged**
