### PR TITLE
Issue #931

### PR DESCRIPTION
**Pull request by BicaniWolfie**
# Description

The changes solves issue [#931](https://github.com/aau-giraf/weekplanner/issues/931), which regards choice boards becoming regular activity cards when a pictogram is selected in the choice board by a citizen. 

This was solved by adding a new attribute to ActivityModel, which makes it so that it can keep track of the chosen pictogram. This then made it possible to select a specific pictogram for a citizen, whilst also making it possible to disregard this change when it is rendered for a guardian. This change is dependant on the corresponding commit to the api_client respository.
## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Android: The test was carried out using Visual Studio Code and Android Studio

* Flutter version: 3.3.8
* Dart version: 2.18.4

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, if necessary
- [ ] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works, if necessary
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [x] I have Acceptance Tested this on an Android device

### CODE REVIEW

**Comment by jsondergaard** [comment]
Har i set de fejl linteren giver?

Når det er fikset, kan i bare pushe og trykke "ready for review" nedenunder :-)

**Comment by BicaniWolfie** [comment]
Vigtig info.
Dette commit er afhængig af [et andet pull request](https://github.com/aau-giraf/api_client/pull/132), som blev lavet til api-client

**Review by jsondergaard — APPROVED** [review]
lgtm

**Review by lodberg1999 — APPROVED** [review]
lgtm

**Pull request merged**
