### PR TITLE
#272 Added text to cancel button 

### LINKED ISSUE #272: The cancel activity button on the showActivityScreen for guardian should also say "aflys"

### PR DESCRIPTION
**Pull request by jenspetur94**
fixes #272

image

image

### CODE REVIEW

**Review by User12837985123 — DISMISSED** [review]

**Comment by Last16** [comment]
In mark mode, "Annullér" is used rather than "Aflys". One of them should be changed to be consistent.

**Comment by jenspetur94** [comment]
> In mark mode, "Annullér" is used rather than "Aflys". One of them should be changed to be consistent.

this is already fixed in another pr where it is changed to Aflys @Last16

**Review by User12837985123 — APPROVED** [review]

**Comment by swuf** [comment]
What about when you are on the ActivityScreen and in citizen mode, then there is no text on the button?

**Comment by jenspetur94** [comment]
> What about when you are on the ActivityScreen and in citizen mode, then there is no text on the button?

There shouldn't be any text for the citizen because we should minimize the amount of text as much as possible for the citizens. 
The customer felt that the cancel icon was ambiguous while the done icon was pretty self explanatory @swuf

**Review by swuf — APPROVED** [review]

**Pull request merged**
