### PR TITLE
Feature/571

### LINKED ISSUE #571: As a guardian I would like to be able to change how many days are shown in the week plan depending on the orientation of the device
**Describe the solution you'd like**
In the settings menu it should be possible to select a different number of days to be visible in the week plan for a citizen depending on whether the device is in landscape or portrait mode.

Default should be 1 for portrait mode.

Related issue: #569 

**Additional context**

### PR DESCRIPTION
**Pull request by Lildhansen**
Related to [this](https://github.com/aau-giraf/api_client/pull/119) Pull request
# Description
Implemented the functionality for the feature, so that the days shown in a weekplanner is changed based on 2 values (one for landscape and one for portrait mode) from the settingsmodel.
Furthermore, another settings screen would have to be added to the main settings screen.
To this end the settings screen for the number of days screen has been updated to act as both the settings screen for landscape and portrait, depending on a boolean value in the constructor.
Moreover, the general abstraction/readability has been improved in the settings menu and the weekplan screen regarding the device orientation.

Finally, unit tests have been updated in the weekplan screen to be for landscape mode (as this is the default screen), but they have not been made for portrait mode, as we were unable to test this in a unit test.
The settings screen has also been tested based on the changes/options made

Fixes #571 

## Type of change
*Delete unchecked boxes (only for Type of change)*

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Unit tests have been made, and all tests have been run with flutter test --coverage

Since the settings screen is still not working, the changes can be tested for portrait mode by changing within the file the:
"_settingsModel.nrOfDaysToDisplayPortrait" variable in the weekplan_screen.dart. This variable must be changed before the assignments done in line 353-359.
The values it can be assigned to are 1, 2, 5, and 7.
if it is changed to 1 or 2, the "_settingsModel.displayDaysRelativePortrait" should also be set to true
if it is changed to 5 or 7, the "_settingsModel.displayDaysRelativePortrait" should be set to false

**Development Configuration**
*Type "flutter --version" and "dart --version" in your CMD to check versions.*

* Flutter version: 2.0.5
* Dart version: 2.12.3

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas, if necessary
- [x] I have made corresponding changes to the documentation, if necessary
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works, if necessary
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have Acceptance Tested this on an iOS device
- [ ] I have Acceptance Tested this on an Android device

### CODE REVIEW

**Comment by Lildhansen** [comment]
testene fejler, eftersom api client ændringerne ikke er blevet merged endnu, men hvis api client ændringerne merges fejler weekplanneren for alle

**Comment by Lildhansen** [comment]
Men hvis man vil få testene til at køre, kan man hente det lokalt, og ændre pubspec.yaml til at hente fra denne branch i stedet "settingsForWeekplanner571" for develop.
Derefter skal man køre: 
flutter pub upgrade api_client

**Review by henr9533 — DISMISSED** [review]
Som beskrevet så kører testene fint, hvis man pejer på den rigtige branch ift. api-client

**Review by JonasStjerne — DISMISSED** [review]

**Comment by Bisgaard01** [comment]
Husk at køre flutter pub upgrade api_client og commit pubspec.lock med de nye changes så alle ikke selv skal gøre det. Skal først gøres når api_client pr er merged ind i develop.

**Comment by manfredhod** [comment]
There are a few info errors in the linter on GitHub actions. Here are a few examples:
   info • AVOID lines longer than 80 characters • lib/screens/weekplan_screen.dart:354:1 • lines_longer_than_80_chars
   info • Unused import: 'package:mockito/mockito.dart' • test/screens/weekplan_screen_test.dart:14:8 • unused_import
 These errors in the linter will make GitHub Actions fail no matter what, and the test will, therefore, not run at all.

**Pull request merged**
