### PR TITLE
Releasefix #186

### LINKED ISSUE #186: Issue #51 Release fix
- **BUG** The weekplan will not save, if there are emojis in the Title (Gives an exception)
- **BUG** When added too much text to the title, it can be hidden, and will overflow the box (See screenshots)
- **BUG** A weekplan can have no name if a space is entered, this can be confusing
IMG_0007
58613054_435300247030845_7260625540824956928_n

### PR DESCRIPTION
**Pull request by ChristianBroS**
This closes #186. 
Emojis can no longer be entered in the title field. This is done by Regex whitelisting. If anyone has a better way to do this, please let us know.

The weekplan_selector_screen now renders overflow titles in the following way:
image

### CODE REVIEW

**Comment by KVISDAOWNER** [comment]
@aau-giraf/sw613f19  you have been assigned this. Here's your checklist. I marked @ralled96  as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [x] Could this code, to the best of your knowledge, have reused existing code?
- [x] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [x] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [x] Do the tests cover sensible cases? Both happy paths and exception paths?
- [x] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [x] Are error messages in the code understandable?
- [x] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [x] Are the features that the code claims to implement, actually implemented?
- [x] Does it look like the code has bugs?
- [x] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [x] Are UI messages, that the user might meet, actually helpful?
- [x] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [x] Is there well written code in this? Remember to tell the developer!

**Comment by KVISDAOWNER** [comment]
@aau-giraf/sw602f19  you have been assigned this. Here's your checklist. I marked @thomaslhansen  as the reviewer, but you might change it as you like.
Please use the following checklist. Feel free to check it off as you go along.
**Code Design**
- [x] Is the code in the right place? (Both in terms of folder structure and class structure)
- [x] Could this code, to the best of your knowledge, have reused existing code?
- [x] Is the code over-engineered? Examples of over-engineering: Implemented behavior for future problems
- [x] Does it introduce functionality that is not necessary for solving the problem?

**Code Readability and Maintainability**
- [x] Are names meaningful and self-documenting?
- [x] Is it understandable, by reading the code, what it does?
- [x] Is the code simple and readable? i.e. it contains no “hack”, or obscure solution.
- [x] Is it understandable, by reading the tests, what they do?
- [x] Do the tests cover sensible cases? Both happy paths and exception paths?
- [x] Do the tests cover the full functionality? i.e., will the tests fail if some of the requested functionality is missing?
- [x] Are error messages in the code understandable?
- [x] Are confusing sections of code covered by comments?

**Functionality**
For this part, open the app, and test:
- [x] Are the features that the code claims to implement, actually implemented?
- [x] Does it look like the code has bugs?
- [x] Are all new screens reachable through in-app navigation?

**Points for Discussion and Reflection**
- [x] Are UI messages, that the user might meet, actually helpful?
- [x] Are there errors that are bad practice? Like, hard-coding a test database connection?
- [x] Is there well written code in this? Remember to tell the developer!

**Review by MathiasLybech — APPROVED** [review]
PO approved

**Review by thomaslhansen — APPROVED** [review]

**Review by LukasRH — APPROVED** [review]
@aau-giraf/sw613f19 Looks good

**Pull request merged**
